batch_size: 4
checkpointing_limit: 0
checkpointing_steps: 0
data_root: /home/azureuser/cloudfiles/code/Users/dieter.holstein/runs/DataPreparation/CogVideo/SmallSplit/Train
do_validation: true
enable_packing: false
gen_fps: 16
gradient_accumulation_steps: 1
learning_rate: 5.0e-06
log_level: INFO
mixed_precision: bf16
model_name: cogvideox1.5-i2v
model_path: /mnt/models/CogVideoX1.5-5B-I2V
name4train: i2v-train
no_grad_sync_when_accumulating: false
num_workers: 32
offload_params_grads: false
output_dir: /home/azureuser/cloudfiles/code/Users/dieter.holstein/runs/HuggingFace/CogKitFix/outputTest
pin_memory: true
report_to: null
resume_from_checkpoint: null
seed: 42
strategy: DDP
train_epochs: 7
train_resolution:
- 17
- 768
- 768
training_type: lora
validation_steps: 0
